# Site settings
title: Learn fsharp because I'm learning, too
email: jlkroeze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Use fsharp for fun and profit and to harness data sources, 
  including web forms, json, and xlsx (Microsoft Excel).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jacobkroeze.com" # the base hostname & protocol for your site
twitter_username: jacobkroeze
github_username:  jacob-kroeze

# Build settings
markdown: kramdown
exclude: [vendor]
